"""empty message

Revision ID: ea4c4d96791e
Revises: 29bd52075910
Create Date: 2024-04-02 22:46:34.801144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4c4d96791e'
down_revision = '29bd52075910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('homeplanet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeplanet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
